### ISSUE TITLE
[Bug]: Failed to parse AndroidManifest.xml

### ISSUE THREAD

**Issue by RawatAshish11** [apivideo/api.video-flutter-uploader#16]
### Version

1.2.2

### Environment that reproduces the issue

Macbook M1 2020
OS- Sonoma
Flutter version - 3.16.5

### Is it reproducible in the example application?

Yes

### Reproduction steps

I'm getting issue after adding this tag in my manifest file

 <service
            android:name="androidx.work.impl.foreground.SystemForegroundService"
            android:foregroundServiceType="location|dataSync"
            tools:node="merge" />

### Expected result

It should be running as mentioned in  video_uploader: ^1.2.2 package readme. But I'm facing issue in my manifest after adding service tag

### Actual result

<img width="1440" alt="Screenshot 2024-02-27 at 6 13 14 PM" src="https://github.com/apivideo/api.video-flutter-uploader/assets/83635075/9012d3b0-f13f-4ed5-9206-3ba26ae50792">

**Comment by ThibaultBee** [comment]
Hi,

There is a syntax error in your `AndroidManifest.xml`. If you are looking for an example, you can have a look at: https://github.com/apivideo/api.video-flutter-uploader/blob/main/example/android/app/src/main/AndroidManifest.xml

**Comment by RawatAshish11** [comment]
here is my android manifest. Everthing is same as mentioned in example still facing issue in service tag

<img width="1440" alt="Screenshot 2024-02-29 at 10 05 12 AM" src="https://github.com/apivideo/api.video-flutter-uploader/assets/83635075/05264cd6-f69e-4425-a7f4-d5e1c0c1ec36">

**Comment by ThibaultBee** [comment]
Ok, I try on my side.
It seems the reason is the `tools:node="merge'`
Could you replace the `service` section by:
```
      <service
            android:name="androidx.work.impl.foreground.SystemForegroundService"
            android:foregroundServiceType="dataSync"
            android:exported="false" />
```

If this fixes your problem, I will update the documentation.

**Comment by ThibaultBee** [comment]
This issue is considered as stalled.
Please reopen it if you need support
